# Generated by Django 5.0.3 on 2024-03-22 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('med_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('composition', models.CharField(max_length=70)),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('cost_per_tab', models.IntegerField()),
                ('mrp_per_tab', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity_supplied', models.IntegerField()),
                ('purchase_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('contact', models.CharField(max_length=25)),
                ('store_runner', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('trans_date', models.DateField()),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('exp_date__lte', '2030-01-01')), name='exp_date_check'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('mfg_date__gte', '2018-01-01')), name='mfg_date_check'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='dealer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dealer'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='med_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_med_id', to='myapp.medicine'),
        ),
        migrations.AddField(
            model_name='quant',
            name='med_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quant_med_id', to='myapp.medicine'),
        ),
        migrations.AddField(
            model_name='quant',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='med_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_med_id', to='myapp.medicine'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
        ),
        migrations.AddConstraint(
            model_name='quant',
            constraint=models.UniqueConstraint(fields=('med_id', 'store_id'), name='unique_quant_entry'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(check=models.Q(('quantity_supplied__lte', 500)), name='quantity_supplied_check'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('purchase_id', 'med_id', 'store_id', 'dealer_id'), name='unique_retail_entry'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('quantity__lte', 150)), name='transaction_quantity_check'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('trans_date__gt', '2018-01-01'), ('trans_date__lt', '2030-01-01')), name='transaction_date_check'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('bill_id', 'med_id'), name='unique_transaction_entry'),
        ),
    ]
